### ISSUE TITLE
Switching Repositories doesn't work

### ISSUE THREAD

**Issue by lnryan** [springernature/halfpipe#5] opened 2019-05-10 11:42 UTC
Hi there,

Today I tried using halfpipe with a public repo outside springernature. I accidentally referenced the wrong repository (one that did not exist yet on my user account). Obviously it hung. 

When I corrected this in `.halfpipe.io.yml` and redid `halfpipe upload,` the linter recognized the change, but the pipeline still did not pick up changes to the correctly specified repository.

When I forked the original to my own account - thereby creating the originally expected one on my user account - it picked it up immediately.

This suggests that while halfpipe can accept a change to the source repo, it does not actually pick up this change in the pipeline.

just fyi.

**Comment by robwhitby** [comment] 2019-05-21 12:45
Can't figure out what the problem is so closing. Can always re-open if it happens again and we can try to debug better.

**Closed by robwhitby** 2019-05-21 12:45 UTC
Labels: bug
