### ISSUE TITLE
A way to trigger CDCs across build systems

### ISSUE THREAD

**Issue by npryce-springer** [springernature/halfpipe#10] opened 2019-05-29 13:48 UTC
We have many services built by App Anatomy and depend on Identity services that are also built by App Anatomy.   We rely on CDC tests to ensure we remain compatible.

To assist migration to Concourse / Halfpipe, we'd like a method to trigger CDC test runs across build servers.    E.g. for a component that is built by Concourse to trigger CDC builds in GoCD, and vice versa.

I'd be happy to use a temporary, tactical solution.  I'm not requesting full-blown, strategic solution for CDC testing.  E.g. I'd be happy to copy scripts into the repo and call them from app-anatomy hooks.  Or add pipeline stages to our builds that trigger pipelines in other build systems.

**Comment by jason-annadani-springer** [comment] 2019-05-29 15:48
yes please - as it stands, we would have to migrate anura and identity to halfpipe together.  that can't be right. and only today, we had another live issue (in admin portal) that was caused by lack of CDC because there was no support for the consumer team being on halfpipe and us being in gocd.

**Comment by robwhitby** [comment] 2019-06-06 15:47
We're thinking about what we could do to make this better. This is how I think it works as-is.

### Scenario: Provider still in GoCD, consumer migrated

For the consumer tests to be discovered and included in the provider pipeline, the consumer repo must have:

* `app-anatomy.yml` with just `runtime-dependencies`
 (it is then processed by the webhook dependency processor - does not need to be a valid pipeline or pass any other linting)

* `docker-compose.yml` with `code` service for running the tests in

* `ci/run-external-and-cdc-<env>`
 (where `<env>` matches provider environment or there is a mapping in the runtime-dependencies)


When the provider runs the tests it will try to lookup the version of the consumer running in CF. It expects it to be found at:

```
if env == live|staging
    <app-name>-<env>.live.cf.private.springer.com/internal/version
else
    <app-name>-<env>.dev.cf.private.springer.com/internal/version
```
If this fails for any reason, it will fall back and run tests in HEAD of consumer.

**Comment by robwhitby** [comment] 2019-06-11 10:58
Unfortunately it turns out it doesn't fall back to `HEAD` if the lookup of `<app-name>-<env>.<dev|live>.cf.private.springer.com/internal/version` fails.

Despite the log:
`Could not retrieve version info from http://ee-test-consumer3-dev.dev.cf.private.springer.com/internal/version so using "master"`

Actually it just `exits 0` after that - it does not run the tests :(

https://github.com/springernature/te-run-dependant-cdcs/blob/master/run_dependant_cdcs/run_dependant_cdcs.py#L194

```if commit_hash_of_version_of_dependant_in_same_environment == 'master':
            return```

So this means that CDCs will only work for consumers in the on-premise CF because the consumer has to be available at the hard-coded route.

**Comment by robwhitby** [comment] 2019-06-26 10:12
### Scenario: Provider migrated to halfpipe, consumer still in GoCD

The consumer's tests will no longer be run in the provider pipeline. They need to be configured manually with the halfpipe `consumer-integration-test` task. either in the `pre_promote` stage of `deploy-cf` or a separate task after deployment.

**Comment by asioli-springer** [comment] 2019-06-26 14:18
Andras and I are having a look at running cdcs in halfpipe and gocd, we are following the documentation here: https://docs.halfpipe.io/legacy-cdcs/ . We have noticed a few things that we would like to share with respect to the case when the supplier is deployed to halfpipe and the consumer to gocd. Our favourite option would be to run cdcs in halfpipe against a temporary version, before deployment. What we have found is that:

- It looks like even when the consumer is a module inside a repo that contains multiple projects, the cdcs are run from the top-level directory; this is in contrast with gocd, and can potentially cause problems as the same script needs to be run on both CI systems (it's causing issues with paths).
- The documentation mentions a "TEST_ROUTE", which we interpreted as an environment variable containing the hostname of the temporary application on halfpipe; however, that environment variable is null. How can we access that? is "TEST_ROUTE" just a placeholder?
- All the cdc scripts need to be modified to read the "test route" and specify this value in the app configuration for cdc tests, falling back to a default when this is not available (for example, on gocd)

We will continue with the investigation, please let us know if you have any questions or comments

**Comment by robwhitby** [comment] 2019-06-26 15:10
> It looks like even when the consumer is a module inside a repo that contains multiple projects, the cdcs are run from the top-level directory; this is in contrast with gocd, and can potentially cause problems as the same script needs to be run on both CI systems (it's causing issues with paths).

it runs whatever you put for `script` in the `consumer-integration-test` task. So you could put `cd sub-dir; ./run-my-test.sh`

> The documentation mentions a "TEST_ROUTE", which we interpreted as an environment variable containing the hostname of the temporary application on halfpipe; however, that environment variable is null. How can we access that? is "TEST_ROUTE" just a placeholder?

> All the cdc scripts need to be modified to read the "test route" and specify this value in the app configuration for cdc tests, falling back to a default when this is not available (for example, on gocd)

CDCs do not need to read `$TEST_ROUTE` directly. It is used as default for the `provider_host` param. The `provider_host` param ends up being set as `$<PROVIDER-APP-NAME>_DEPLOYED_HOST` to match the old CDC expectations. Here is the code that generates the `consumer-integration-test` task. It probably explains it better than me.

https://github.com/springernature/halfpipe/blob/master/pipeline/consumer_integration_test_job.go

I don't think there is any reason to have to update the consumer CDC scripts.

**Comment by andrasgaal** [comment] 2019-07-01 14:21
It looks like the content of `script` has to be an executable. If we use `cd sub-dir; ./run-my-test.sh` it complains. However we overcome this issue by creating another script like `run-external-and-cdcs-staging-halfpipe` in the consumer repo  which is doing the `cd` and calling the existing script. Then we call this new script from the provider's `consumer-integration-test`.
Another thing to note is what URL the consumer should call. If the CDC is running from halfpipe, the `$<PROVIDER-APP-NAME>_DEPLOYED_HOST` environment variable is set and the test should use it because this is the new candidate. However if this variable is not available that means the test is running in GoCD and it should fall back to the URL of the deployed application.

**Comment by robwhitby** [comment] 2019-07-01 16:48
sorry, my mistake, you can write the `script` like this instead of having to modify the consumer repo:
```bash -c 'cd sub-dir && ./run-my-test.sh'```

> Another thing to note is what URL the consumer should call. If the CDC is running from halfpipe, the `$<PROVIDER-APP-NAME>_DEPLOYED_HOST` environment variable is set and the test should use it because this is the new candidate. However if this variable is not available that means the test is running in GoCD and it should fall back to the URL of the deployed application.

I don't think that is correct, the same env var is set by GoCD. 

Here's some docs on GoCD side of things: http://ee-docs.apps.dc.springernature.io/release_engineering/cdcs/#providers 

and an example: http://05.gocd.tools.engineering/go/admin/pipelines/springer-user-service/stages/run-dependants-cdcs-live/job/run-dependant-cdcs-live-idp-nature_individual-service/tasks

Let me know if that all makes sense

**Comment by robwhitby** [comment] 2019-07-18 10:42
@npryce-springer @jason-annadani-springer are you satisfied we can close this issue? I don't think we have found the need for any additional work.

**Comment by andrasgaal** [comment] 2019-07-18 13:47
Sorry for not getting back to you sooner Rob. 
Your script suggestion works fine, thank you.
I wasn't so clear about the `$<PROVIDER-APP-NAME>_DEPLOYED_HOST` injection, sorry about that, let me try to explain it. 
Application A is a provider and using halfpipe while Application B is the consumer of Application A and using app anatomy. If there is a new version of Application A, the consumer-integration-test task will be triggered and Application B's CDCs will have the `$<PROVIDER-APP-NAME>_DEPLOYED_HOST` environment variable, so that's fine. However when there is a new version of Application B, the external-and-cdcs-[environment] task will be executed which does not provide the mentioned environment variable to the CDCs and they have to fall back to use the the hardcoded deployed host URL what they are probably using right now already so it's not a big problem.

**Comment by robwhitby** [comment] 2019-08-20 13:09
I'm closing this issue because we haven't identified any further work needed. Please re-open if I'm wrong

**Closed by robwhitby** 2019-08-20 13:09 UTC
Labels: enhancement
